# Version of the Icarus theme that is currently used
version: 2.3.0
# Path or URL to the website's icon
favicon: /images/favicon-32x32.png
# Path or URL to RSS atom.xml
rss: '/atom.xml'
# Path or URL to the website's logo to be shown on the left of the navigation bar or footer
logo: /images/logo.svg
# Open Graph metadata
# https://hexo.io/docs/helpers.html#open-graph
open_graph:
  # Facebook App ID
  fb_app_id:
  # Facebook Admin ID
  fb_admins:
  # Twitter ID
  twitter_id:
  # Twitter site
  twitter_site:
  # Google+ profile link
  google_plus:
# Navigation bar link settings
navbar:
  # Navigation bar menu links
  menu:
    Home: /
    Archives: /archives
    Categories: /categories
    Tags: /tags
    LeetCode: /leetcode
    Projects: /projects
    About: /about
  # Navigation bar links to be shown on the right
  links:
    Download on GitHub:
      icon: fab fa-github
      url: 'https://github.com/calebman'
# Footer section link settings
footer:
  # Links to be shown on the right of the footer section
  links:
    CC BY-NC-SA 4.0:
      icon:
        - fab fa-creative-commons
        - fab fa-creative-commons-by
        - fab fa-creative-commons-nc
        - fab fa-creative-commons-sa
      url: 'https://creativecommons.org/licenses/by-nc-sa/4.0/'
# Article display settings
article:
  # Code highlight theme
  # https://github.com/highlightjs/highlight.js/tree/master/src/styles
  highlight: xcode
  # Whether to show article thumbnail images
  thumbnail: true
  # Whether to show estimate article reading time
  readtime: true
# Search plugin settings
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Search
search:
  # Name of the search plugin
  type: insight
# Comment plugin settings
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Comment
comment:
  type: gitalk
  owner: calebman
  repo: blog
  client_id: bd0cbb30da9c24da8c7c
  client_secret: bd64a8e8c8117d5f3e22291cd3f29f2c70e671ff
  admin: calebman
# Share plugin settings
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Share
share:
  # Share plugin name
  type:
# Sidebar settings.
# Please be noted that a sidebar is only visible when it has at least one widget
sidebar:
  # left sidebar settings
  left:
    # Whether the left sidebar is sticky when page scrolls
    # https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/make-a-sidebar-sticky-when-page-scrolls/
    sticky: true
  # right sidebar settings
  right:
    # Whether the right sidebar is sticky when page scrolls
    # https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/make-a-sidebar-sticky-when-page-scrolls/
    sticky: true
# Sidebar widget settings
# https://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/
widgets:
  - # Widget name
    type: profile
    # Where should the widget be placed, left or right
    position: left
    # Author name to be shown in the profile widget
    author: JianhuiChen
    # Title of the author to be shown in the profile widget
    author_title: Web Developer
    # Author's current location to be shown in the profile widget
    location: TianJin, China
    # Path or URL to the avatar to be shown in the profile widget
    avatar: /images/avatar.png
    # Email address for the Gravatar to be shown in the profile widget
    gravatar:
    # Whether to show avatar image rounded or square
    avatar_rounded: true
    # Path or URL for the follow button
    follow_link: 'https://github.com/calebman'
    # Links to be shown on the bottom of the profile widget
    social_links:
      Github:
        icon: fab fa-github
        url: 'https://github.com/calebman'
      掘金:
        icon: fab fa-pagelines
        url: 'https://juejin.im/user/59bc7c00f265da0644289a4b'
      RSS:
        icon: fas fa-rss
        url: /atom.xml
  - # Widget name
    type: toc
    # Where should the widget be placed, left or right
    position: left
  - # Widget name
    type: links
    # Where should the widget be placed, left or right
    position: left
    # Links to be shown in the links widget
    links:
      FriendsMap.neoy.blog.url: https://neoy.site/
      FriendsMap.huangcong.blog.url: https://huangcong.site/
      Java HashMap工作原理及实现: http://www.importnew.com/18633.html
      红黑树的原理在线示例: https://www.cs.usfca.edu/~galles/visualization/RedBlack.html
  - # Widget name
    type: category
    # Where should the widget be placed, left or right
    position: left
  - # Widget name
    type: tagcloud
    # Where should the widget be placed, left or right
    position: left
  - # Widget name
    type: recent_posts
    # Where should the widget be placed, left or right
    position: right
  - # Widget name
    type: archive
    # Where should the widget be placed, left or right
    position: right
  - # Widget name
    type: tag
    # Where should the widget be placed, left or right
    position: right
# Other plugin settings
plugins:
  # Enable page animations
  animejs: true
  # Enable the lightGallery and Justified Gallery plugins
  # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/gallery-plugin/
  gallery: true
  # Enable the Outdated Browser plugin
  # http://outdatedbrowser.com/
  outdated-browser: true
  # Enable the MathJax plugin
  # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/mathjax-plugin/
  mathjax: true
  # Show the back to top button on mobile devices
  back-to-top: true
  # Google Analytics plugin settings
  # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/site-analytics-plugin/#Google-Analytics
  google-analytics:
    # Google Analytics tracking id
    tracking_id:
  # Baidu Analytics plugin settings
  # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/site-analytics-plugin/#Baidu-Analytics
  baidu-analytics:
    # Baidu Analytics tracking id
    tracking_id:
  # Hotjar user feedback plugin
  # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/site-analytics-plugin/#Hotjar
  hotjar:
    # Hotjar site id
    site_id: 19960428
  # Show a loading progress bar at top of the page
  progressbar: true
  # Show the copy button in the highlighted code area
  clipboard: true
  # BuSuanZi site/page view counter
  # https://busuanzi.ibruce.info
  busuanzi: false
# CDN provider settings
# https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/speed-up-your-site-with-custom-cdn/
providers:
  # Name or URL of the JavaScript and/or stylesheet CDN provider
  cdn: jsdelivr
  # Name or URL of the webfont CDN provider
  fontcdn: google
  # Name or URL of the webfont Icon CDN provider
  iconcdn: fontawesome
